import 'package:fluent_ui/fluent_ui.dart';
import 'package:phosphor_flutter/phosphor_flutter.dart';

const defaultQuizCategoryIcon = 'gameController';
const defaultQuizCategoryColor = 0xFF6366F1;

const quizCategoryColors = [
  Color(0xFF6366F1),
  Color(0xFF8B5CF6),
  Color(0xFFEC4899),
  Color(0xFFEF4444),
  Color(0xFFF59E0B),
  Color(0xFF84CC16),
  Color(0xFF10B981),
  Color(0xFF14B8A6),
  Color(0xFF3B82F6),
  Color(0xFF64748B),
];

final Map<String, IconData> quizCategoryIcons = {
  'acorn': PhosphorIconsFill.acorn,
  'airplane': PhosphorIconsFill.airplane,
  'alarm': PhosphorIconsFill.alarm,
  'anchor': PhosphorIconsFill.anchor,
  'atom': PhosphorIconsFill.atom,
  'backpack': PhosphorIconsFill.backpack,
  'balloon': PhosphorIconsFill.balloon,
  'barbell': PhosphorIconsFill.barbell,
  'basketball': PhosphorIconsFill.basketball,
  'bell': PhosphorIconsFill.bell,
  'bicycle': PhosphorIconsFill.bicycle,
  'bird': PhosphorIconsFill.bird,
  'bomb': PhosphorIconsFill.bomb,
  'book': PhosphorIconsFill.book,
  'bookOpen': PhosphorIconsFill.bookOpen,
  'brain': PhosphorIconsFill.brain,
  'bread': PhosphorIconsFill.bread,
  'briefcase': PhosphorIconsFill.briefcase,
  'bug': PhosphorIconsFill.bug,
  'butterfly': PhosphorIconsFill.butterfly,
  'cactus': PhosphorIconsFill.cactus,
  'cake': PhosphorIconsFill.cake,
  'calculator': PhosphorIconsFill.calculator,
  'calendar': PhosphorIconsFill.calendar,
  'camera': PhosphorIconsFill.camera,
  'campfire': PhosphorIconsFill.campfire,
  'car': PhosphorIconsFill.car,
  'carrot': PhosphorIconsFill.carrot,
  'cat': PhosphorIconsFill.cat,
  'chartBar': PhosphorIconsFill.chartBar,
  'chatCircle': PhosphorIconsFill.chatCircle,
  'cherries': PhosphorIconsFill.cherries,
  'church': PhosphorIconsFill.church,
  'clock': PhosphorIconsFill.clock,
  'cloud': PhosphorIconsFill.cloud,
  'clover': PhosphorIconsFill.clover,
  'coffee': PhosphorIconsFill.coffee,
  'coins': PhosphorIconsFill.coins,
  'compass': PhosphorIconsFill.compass,
  'confetti': PhosphorIconsFill.confetti,
  'cookie': PhosphorIconsFill.cookie,
  'cow': PhosphorIconsFill.cow,
  'crown': PhosphorIconsFill.crown,
  'cube': PhosphorIconsFill.cube,
  'detective': PhosphorIconsFill.detective,
  'diamond': PhosphorIconsFill.diamond,
  'diceFive': PhosphorIconsFill.diceFive,
  'dog': PhosphorIconsFill.dog,
  'egg': PhosphorIconsFill.egg,
  'envelope': PhosphorIconsFill.envelope,
  'fire': PhosphorIconsFill.fire,
  'fish': PhosphorIconsFill.fish,
  'flag': PhosphorIconsFill.flag,
  'flask': PhosphorIconsFill.flask,
  'flower': PhosphorIconsFill.flower,
  'football': PhosphorIconsFill.football,
  'forkKnife': PhosphorIconsFill.forkKnife,
  'gameController': PhosphorIconsFill.gameController,
  'ghost': PhosphorIconsFill.ghost,
  'gift': PhosphorIconsFill.gift,
  'globe': PhosphorIconsFill.globe,
  'graduationCap': PhosphorIconsFill.graduationCap,
  'guitar': PhosphorIconsFill.guitar,
  'hamburger': PhosphorIconsFill.hamburger,
  'hammer': PhosphorIconsFill.hammer,
  'heart': PhosphorIconsFill.heart,
  'horse': PhosphorIconsFill.horse,
  'house': PhosphorIconsFill.house,
  'iceCream': PhosphorIconsFill.iceCream,
  'key': PhosphorIconsFill.key,
  'leaf': PhosphorIconsFill.leaf,
  'lightbulb': PhosphorIconsFill.lightbulb,
  'lightning': PhosphorIconsFill.lightning,
  'lock': PhosphorIconsFill.lock,
  'magicWand': PhosphorIconsFill.magicWand,
  'mapPin': PhosphorIconsFill.mapPin,
  'medal': PhosphorIconsFill.medal,
  'microphone': PhosphorIconsFill.microphone,
  'moon': PhosphorIconsFill.moon,
  'mountains': PhosphorIconsFill.mountains,
  'musicNotes': PhosphorIconsFill.musicNotes,
  'paintBrush': PhosphorIconsFill.paintBrush,
  'palette': PhosphorIconsFill.palette,
  'pawPrint': PhosphorIconsFill.pawPrint,
  'pencil': PhosphorIconsFill.pencil,
  'pizza': PhosphorIconsFill.pizza,
  'planet': PhosphorIconsFill.planet,
  'plant': PhosphorIconsFill.plant,
  'puzzlePiece': PhosphorIconsFill.puzzlePiece,
  'question': PhosphorIconsFill.question,
  'rainbow': PhosphorIconsFill.rainbow,
  'robot': PhosphorIconsFill.robot,
  'rocket': PhosphorIconsFill.rocket,
  'scissors': PhosphorIconsFill.scissors,
  'shield': PhosphorIconsFill.shield,
  'skull': PhosphorIconsFill.skull,
  'smiley': PhosphorIconsFill.smiley,
  'snowflake': PhosphorIconsFill.snowflake,
  'sparkle': PhosphorIconsFill.sparkle,
  'star': PhosphorIconsFill.star,
  'strategy': PhosphorIconsFill.strategy,
  'sun': PhosphorIconsFill.sun,
  'sword': PhosphorIconsFill.sword,
  'target': PhosphorIconsFill.target,
  'tent': PhosphorIconsFill.tent,
  'tree': PhosphorIconsFill.tree,
  'trophy': PhosphorIconsFill.trophy,
  'umbrella': PhosphorIconsFill.umbrella,
  'wallet': PhosphorIconsFill.wallet,
  'waves': PhosphorIconsFill.waves,
  'wind': PhosphorIconsFill.wind,
  'wrench': PhosphorIconsFill.wrench,
};

IconData quizCategoryIconData(String name) {
  return quizCategoryIcons[name] ?? PhosphorIconsFill.gameController;
}
